site_name: Sweepers Inc. Officers Portal

theme:
    name: material


nav:
- Home: index.md
- Rules: rules.md
- About the Guild:
    - About Our Ranks: rank.md
    - GOCC: gocc.md


copyright: Copyright &copy; 2022 Chimney Sweepers

markdown_extentions:

    - toc:
            - permalink: true
            - toc_depth: 2

    - pymdownx.arithmatex:
        generic: true

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
