site_name: Sweepers Inc. Officers Portal

theme:
    name: material


nav:
- Home: index.md
- Dashboards: dashboards.md
- Analytics: analytics.md
- Rules: rules.md
- Rank Change Guide:
    - Non-Officer Promotions: promotions/nonofficer.md
    - Officer Promotions: promotions/officer.md
    - Demotions: promotions/demotion.md
- Verification Guides:
    - Guild Rules: verification/verification.md
    - Verification Guidelines: verification/vg_admin.md
- About the Guild:
    - About Our Ranks: about/rank.md
    - Guild Divisions: about/division.md
    - Recruitment Info: about/recruit.md
    - Guild Analytics: about/gocc.md



copyright: Copyright &copy; 2022 Chimney Sweepers (Sweepers Inc.)

markdown_extentions:

    - toc:
            - permalink: true
            - toc_depth: 2

    - pymdownx.arithmatex:
        generic: true

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
