site_name: Sweepers Inc. Officers Portal

theme:
    name: material
    

nav:
- Home: index.md
- Our Job: roles.md
- About Our Ranks: rank.md
- Process:
    - Raffle: raffle.md


copyright: Copyright &copy; 2022 Chimney Sweepers

markdown_extentions:

    - toc:
            - permalink: true
            - toc_depth: 2

    - pymdownx.arithmatex:
        generic: true

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
